'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const presets={content:{name:'二次元内容运营',raw:'社区业务想招一名二次元内容运营，尽快到岗，要有内容感，也要能和创作者沟通。',goals:['内容选题与社区理解','创作者合作与关系维护','垂类内容增长'],evidence:'通过选题作品、社区运营案例及复盘，验证内容判断与执行过程。',resource:'有创作者沟通或合作经验；具体资源要求待确认。'},growth:{name:'增长投放运营',raw:'增长组希望招一名投放运营，能看数据，做过转化优化，最好尽快到岗。',goals:['投放转化与实验复盘','素材策略与迭代','预算分配与效果分析'],evidence:'通过投放实验案例，验证指标口径、归因分析和优化方法。',resource:'能与素材、产品和数据团队协作；协作范围待确认。'},intern:{name:'CNY 项目实习生',raw:'CNY 项目急需实习生协助内容整理和活动执行，希望尽快到岗，沟通及时。',goals:['活动执行与进度跟进','内容整理与信息核验','用户沟通与问题记录'],evidence:'通过活动执行或内容整理案例，验证细致程度、反馈与推进能力。',resource:'能及时反馈进度、与项目成员协作；具体出勤要求待确认。'},custom:{name:'自定义岗位',raw:'',goals:['待业务明确首要交付','执行与协作','分析与复盘'],evidence:'请填写与岗位直接相关的可观察证据。',resource:'请填写岗位需要的协作方式。'}};
let state={scenario:'content',name:'社区内容运营',raw:'',rows:[],version:0,history:[],pending:null,feedback:[],checks:{},undo:null,kind:'business'};
const fixture=[{name:'虚拟候选人 A',excerpt:'在校园运营 ACG 内容账号，负责选题与发布；组织社团活动，与参与者沟通。',note:'已描述选题与活动沟通；未说明商业创作者合作。'},{name:'虚拟候选人 B',excerpt:'参与游戏社区运营，与外部内容创作者沟通合作安排并记录交付。',note:'已描述合作经历；合作对象、本人职责与可迁移范围待核验。'},{name:'虚拟候选人 C',excerpt:'制作动漫评论视频，提供个人作品集；未填写团队协作经历。',note:'可查看内容作品；未描述协作经历，不据此推断不具备能力。'}];
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',3000)}
function row(id,label,text,level,source='规则建议 · 待审阅',confirmed=false){return {id,label,text,level,source,confirmed}}
function generate(){const p=presets[$('scenario').value];const raw=$('raw').value.trim();if(!raw){toast('先输入业务需求，再生成初稿');return false}state.scenario=$('scenario').value;state.name=p.name;state.raw=raw;state.version=0;state.history=[];state.pending=null;state.undo=null;state.checks={};state.rows=[row('goal','业务目标','待确认：'+$('q1').value,'待确认'),row('ability','能力证据',p.evidence,'必须项'),row('resource','协作要求',p.resource,'加分项'),row('tradeoff','关键取舍','尚未确认能力与到岗时间的优先顺序。','待确认'),row('boundary','其他边界','城市、到岗日期和其他条件未确认。','待确认')];render();return true}
function setScenario(){const p=presets[$('scenario').value];$('raw').value=p.raw;$('q1').innerHTML=p.goals.map(g=>`<option>${esc(g)}</option>`).join('');$('extra').value='';if(p.raw)generate();else toast('输入自定义需求后，点击生成初稿')}
function edited(){state.pending=null;state.undo=null;renderMeta();renderTarget();renderImpact();renderOutput()}
function applyAnswers(){if(!state.rows.length)return;const vals={goal:$('q1').value,tradeoff:$('q2').value,boundary:$('extra').value.trim()||'城市、到岗日期和其他条件未确认。'};for(const r of state.rows)if(vals[r.id]){r.text=vals[r.id];r.source='HR 输入 · 请核实业务意见';r.confirmed=false}edited();renderCards();toast('选择已写入初稿，请审阅确认')}
function renderMeta(){const n=state.rows.filter(r=>r.confirmed).length;$('sideTitle').textContent=state.name;$('version').textContent=`当前版本 v${state.version} · ${n}/${state.rows.length} 条确认`;$('changeVersion').textContent=`当前 v${state.version}`;$('confirmedCount').textContent=`${n} / ${state.rows.length} 条标准已确认`}
function renderCards(){$('cards').innerHTML=state.rows.map(r=>`<div class="standard"><div><label for="row-${r.id}">${esc(r.label)}</label><span class="source">${esc(r.level)}</span></div><div><textarea id="row-${r.id}" data-id="${r.id}" rows="2">${esc(r.text)}</textarea><span class="source">${esc(r.source)}</span></div><div><span class="badge ${r.confirmed?'ok':''}">${r.confirmed?'HR 已确认':'待确认'}</span><button data-confirm="${r.id}">${r.confirmed?'撤销确认':'确认本条'}</button></div></div>`).join('');renderMeta()}
function renderTarget(){const current=$('target').value;$('target').innerHTML=state.rows.map(r=>`<option value="${r.id}">${esc(r.label)}</option>`).join('');$('target').value=state.rows.some(r=>r.id===current)?current:'resource'}
function impactFor(r){const common=['同步更新给业务、HR 和面试官的材料。','应用后将现有人工核验状态重置为待核验；保留原始证据。'];if(r.id==='resource')return ['先核实“资源”指可直接合作的关系，还是建立关系的能力。','在寻访中补充对应的协作经历描述；不能仅凭职位名称排除候选人。','逐一核验虚拟候选人的本人职责、合作对象与经验可迁移性。',...common];if(r.id==='boundary'||r.id==='tradeoff')return ['重新向候选人确认到岗、地点和约束，记录可协商空间。','候选人池和招聘周期影响缺少真实数据，当前不作数量预测。',...common];return ['按新标准补充可观察的作品或经历证据。','更新寻访关键词和面试问题，并核验已推进候选人的相关材料。',...common]}
function previewChange(){const r=state.rows.find(x=>x.id===$('target').value);const value=$('newValue').value.trim(),message=$('message').value.trim();if(!r||!value||!message){toast('请填写变更原话和更新后的具体要求');return false}if(value===r.text&&$('newLevel').value===r.level){toast('这条要求没有变化');return false}state.pending={id:r.id,before:{...r},after:value,level:$('newLevel').value,message,impacts:impactFor(r)};renderImpact();return true}
function renderImpact(){const p=state.pending;if(!p){$('impact').innerHTML='<div class="empty">选择标准并预览，即可看到前后差异与复核建议。预览不会修改当前版本。</div>';return}$('impact').innerHTML=`<div class="panel-title"><h2>变更预览</h2><span class="badge">尚未生效</span></div><div class="diff old"><strong>之前 · ${esc(p.before.level)}</strong>${esc(p.before.text)}</div><div class="diff new"><strong>拟调整 · ${esc(p.level)}</strong>${esc(p.after)}</div><h2>需要跟进的工作</h2><ul class="impact-list">${p.impacts.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p class="fine">这是一份规则驱动的复核清单，不是对候选人数、招聘周期或匹配度的预测。</p><button id="commitChange" class="primary">确认并应用到 v${state.version+1}</button> <button id="cancelChange">取消预览</button>`}
function commitChange(){if(!state.pending)return;const p=state.pending;state.undo={rows:structuredClone(state.rows),checks:structuredClone(state.checks)};const r=state.rows.find(x=>x.id===p.id);Object.assign(r,{text:p.after,level:p.level,source:'HR 确认的变更 · '+p.message,confirmed:true});state.version++;state.history.unshift({...p,version:state.version,time:new Date().toLocaleTimeString('zh-CN')});state.checks={};state.pending=null;render();toast('已应用，招聘材料已同步更新')}
function undo(){if(!state.undo)return;state.rows=state.undo.rows;state.checks=state.undo.checks;state.version++;state.history.unshift({version:state.version,time:new Date().toLocaleTimeString('zh-CN'),revert:true});state.undo=null;state.pending=null;render();toast('已恢复变更前标准，并保留撤销记录')}
function renderCandidates(){$('candidates').innerHTML=fixture.map((c,i)=>`<div class="person"><strong>${esc(c.name)}</strong><div><blockquote>“${esc(c.excerpt)}”</blockquote><p>${esc(c.note)}</p><span class="fine">按当前岗位标准人工核验；该示例证据不会随要求改变而被重写。</span></div><select data-person="${i}" aria-label="${esc(c.name)}的核验状态">${['待核验','已向候选人追问','相关证据已核实'].map(s=>`<option ${state.checks[i]===s?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')}
function renderHistory(){$('history').innerHTML=state.history.length?state.history.map((h,i)=>`<div class="historyitem"><strong>v${h.version} · ${h.revert?'撤销最近变更':esc(h.before.label)+'已更新'}</strong><span class="source">${h.time}</span>${h.revert?'':`<p>业务原话：${esc(h.message)}</p><p>${esc(h.before.text)} → ${esc(h.after)}</p>`}${i===0&&state.undo?'<button id="undo">撤销最近一次应用</button>':''}</div>`).join(''):'<p class="muted">尚无已应用变更。草稿编辑不计作业务确认。</p>'}
function getOutput(){const get=id=>state.rows.find(r=>r.id===id)?.text||'';const line=r=>`[${r.confirmed?'HR 已确认':'待确认'} / ${r.level}] ${r.label}：${r.text}\n来源：${r.source}`;let s=`${state.name}｜v${state.version}\n业务原话：${state.raw}\n\n`;if(state.kind==='business')s+='请业务确认以下岗位标准及取舍：\n\n'+state.rows.map(line).join('\n\n');if(state.kind==='sourcing')s+=`寻访目标：${get('goal')}\n关键取舍：${get('tradeoff')}\n边界：${get('boundary')}\n\n搜索起点（规则建议，需验证）：\n${state.scenario==='content'?'二次元 / ACG / 内容策划 / 社区运营；根据优先目标扩展创作者运营或内容增长经历。':state.scenario==='growth'?'增长投放 / 转化优化 / 实验复盘；核实指标与本人职责。':state.scenario==='intern'?'活动执行 / 内容整理 / 校园项目；核实出勤与开始时间。':'根据确认后的业务目标填写关键词；当前无自动市场检索。'}\n\n需要的经历证据：\n${line(state.rows.find(r=>r.id==='ability'))}\n\n${line(state.rows.find(r=>r.id==='resource'))}\n\n取舍提示：${get('tradeoff').includes('时间优先')?'先确认可到岗时间，对可培养项单独评估；不要擅自放宽必须项。':'先核实关键经历与作品，再与业务协商时间约束。'}`;if(state.kind==='interview')s+=`本轮目标：${get('goal')}\n\n验证要求：\n${state.rows.filter(r=>['ability','resource'].includes(r.id)).map(line).join('\n\n')}\n\n建议追问（需结合简历调整）：\n1. 请用一个案例说明你如何完成「${get('goal')}」，你本人负责哪部分？\n2. 针对「${get('ability')}」，可以展示哪些作品、过程或复盘证据？\n3. 针对「${get('resource')}」，有哪些相关合作案例？哪些信息还需要确认？\n\n记录方式：候选人原话 → 已验证事实 → 待追问项。\n缺少简历描述不等于缺少能力。`;return s+'\n\n说明：交互 Demo，规则模拟；未进行市场检索或自动筛选。'}
function renderOutput(){$('outTitle').textContent={business:'业务确认单',sourcing:'Sourcing Brief',interview:'面试验证提纲'}[state.kind];$('outText').value=getOutput()}
function render(){renderCards();renderTarget();renderImpact();renderCandidates();renderHistory();renderOutput()}
function show(view){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='output')renderOutput();window.scrollTo({top:0,behavior:'smooth'})}
function saveFile(content,name,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('scenario').onchange=()=>{if(state.rows.some(r=>r.confirmed)||state.history.length){if(!confirm('切换场景会替换本次标准和变更记录，请先下载需要保留的内容。继续？')){$('scenario').value=state.scenario;return}}setScenario()};$('generate').onclick=()=>{if(state.rows.some(r=>r.confirmed)||state.history.length){if(!confirm('重新生成会替换本次会话的标准与变更记录，是否继续？'))return}if(generate())toast('已生成初稿；原话已保留，建议需审阅')};$('applyAnswers').onclick=applyAnswers;
$('cards').addEventListener('input',e=>{const id=e.target.dataset.id;if(!id)return;const r=state.rows.find(r=>r.id===id);r.text=e.target.value;r.confirmed=false;r.source='HR 编辑 · 待确认';edited();const item=e.target.closest('.standard');item.querySelector('.badge').textContent='待确认';item.querySelector('.badge').classList.remove('ok');item.querySelector('button').textContent='确认本条';item.querySelector('.source:last-child').textContent=r.source});
$('cards').addEventListener('click',e=>{const id=e.target.dataset.confirm;if(!id)return;const r=state.rows.find(r=>r.id===id);if(!r.text.trim()){toast('请先填写具体标准');return}r.confirmed=!r.confirmed;edited();renderCards()});
$('confirmAll').onclick=()=>{if(state.rows.some(r=>!r.text.trim())){toast('请先补齐空白标准');return}state.rows.forEach(r=>r.confirmed=true);edited();renderCards();toast('已记录 HR 确认；仍需与业务核实取舍')};$('nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)};$('goChange').onclick=()=>show('change');$('previewChange').onclick=previewChange;
['message','target','newValue','newLevel'].forEach(id=>$(id).addEventListener('input',()=>{state.pending=null;renderImpact()}));
$('impact').onclick=e=>{if(e.target.id==='commitChange')commitChange();if(e.target.id==='cancelChange'){state.pending=null;renderImpact()}};$('history').onclick=e=>{if(e.target.id==='undo')undo()};$('candidates').onchange=e=>{if(e.target.dataset.person!==undefined)state.checks[e.target.dataset.person]=e.target.value};
$('outputTabs').onclick=e=>{const b=e.target.closest('[data-kind]');if(!b)return;state.kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));renderOutput()};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('outText').value);toast('已复制招聘材料')}catch{$('outText').focus();$('outText').select();toast('已选中文本，请按 Ctrl+C / ⌘C 复制')}};$('saveText').onclick=()=>saveFile(getOutput(),`招聘材料-v${state.version}.txt`);$('download').onclick=()=>saveFile(JSON.stringify(state,null,2),'招聘对齐工作记录.json','application/json');
$('guideBtn').onclick=()=>$('guide').showModal();$('closeGuide').onclick=()=>$('guide').close();$('feedbackSave').onclick=()=>{const s=$('feedback').value.trim();if(!s){toast('先写下试用发现');return}state.feedback.push(s);$('feedback').value='';$('feedbackList').innerHTML=state.feedback.map(s=>`<p class="diff">${esc(s)}</p>`).join('');toast('已保存，可下载工作记录留存')};
setScenario();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_hiring_brief',title:'读取当前岗位标准',description:'读取当前会话中的岗位标准、确认状态和版本，不修改数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('不接受参数');return {name:state.name,version:state.version,rows:structuredClone(state.rows)}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
